# Gaussian Elimination Project

This is one of my first projects related to Data Science and Machine Learning. In this lab I will implement the Gaussian Elimination method, a foundational algorithm for solving systems of linear equations.

# Outline
- [ 1 - Introduction ](#1)
- [ 2 - Import Numpy](#2)
- [ 3 - Auxiliary functions](#3)
  - [ 3.1 - Function swap rows](#3.1)
  - [ 3.2 - Finding the first non-zero value in a column starting from a specific value](#3.2)
  - [ 3.3 - Find the first non zero element for any row](#3.3)
  - [ 3.4 - Constructing the Augmented Matrix](#3.4)
- [ 4 - Row echelon form](#4)
  - [ 4.1 - Row Echelon Form](#4.1)
  - [ 4.2 - Row Echelon Form function](#4.2)
- [ 5 - Back substitution](#5)
  - [ 5.1 - Back substitution function](#5.1)
- [ 6 - The Gaussian Elimination](#6)
  - [ 6.1 - Bringing it all together](#6.1)
- [ 7 - Test with any system of equations!](#7)


<a name="#1"></a>
## 1 - Introduction 

### Step 1: Augmented Matrix

Consider a system of linear equations:

$$
\begin{align*}
2x_1 + 3x_2 + 5x_3&= 12 \\
-3x_1 - 2x_2 + 4x_3 &= -2 \\
x_1 + x_2 - 2x_3  &= 8 \\

\end{align*}
$$
Create the augmented matrix \([A | B]\), where \(A\) represents the coefficient matrix and \(B\) denotes the column vector of constants:

$$
A = \begin{bmatrix}
\phantom{-}2 & \phantom{-}3 & \phantom{-}5  \\
-3 & -2 & \phantom-4 \\
\phantom{-}1 & \phantom{-}1 & -2  \\
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
\phantom-12 \\ -2 \\ \phantom-8 
\end{bmatrix}
$$

Thus, \([A | B]\) is represented as:

$$
\begin{bmatrix}
\phantom{-}2 & \phantom{-}3 & \phantom{-}5 & | & \phantom{-}12 \\
-3 & -2 & \phantom-4 & | & -2 \\
\phantom{-}1 & \phantom{-}1 & -2 & | & \phantom{-}8 \\
\end{bmatrix}
$$


### Step 2: Transform Matrix into Row Echelon Form
Initiate row operations to convert the augmented matrix into row-echelon form. The objective is to introduce zeros below the leading diagonal.

- **Row Switching:** Rearrange rows to position the leftmost non-zero entry at the top.
- **Row Scaling:** Multiply a row by a non-zero scalar.
- **Row Replacement:** Substitute a row with the sum of itself and a multiple of another row.

### Step 3: Back Substitution

After attaining the row-echelon form, solve for variables starting from the last row and progressing upwards.


### Step 4: Compile the Gaussian Elimination Algorithm

Combine each function related to the aforementioned steps into a single comprehensive function.

<a name="2"></a>
## 2 - Import Numpy

In [6]:
import numpy as np

<a name="3"></a>
## 3 - Auxiliary functions

<a name="3.1"></a>
### 3.1 - Function swap rows

In [10]:
def swap_rows(M, row_index_1, row_index_2):
    M = M.copy()

    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M

I will test our **swap_rows** function with some examples

In [13]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Matrix M before func: \n{M}')
M = swap_rows(M, 0, 2)
print(f'Matrix M after func: \n{M}')

Matrix M before func: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix M after func: 
[[7 8 9]
 [4 5 6]
 [1 2 3]]


<a name="3.2"></a>
### 3.2 - Finding the first non-zero value in a column starting from a specific value

In [16]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    column_array = M[starting_row:, column]

    for i, val in enumerate(column_array):
        if not np.isclose(val, 0, atol = 1e-5):
            index = i + starting_row
            return index
    return -1

Let's test this function

In [19]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [21]:
get_index_first_non_zero_value_from_column(N, 0, 0)

-1

So, as we can see, our function works right!

<a name="3.3"></a>
### 3.3 - Find the first non zero element for any row

This function aids in locating the pivot within a designated row of a matrix. It identifies the index of the first non-zero element in the desired row. If no non-zero value is present, it returns -1.

In [25]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    M = M.copy()

    if augmented == True:
        M = M[:, :-1]
    row_array = M[row]
    for i, val in enumerate(row_array):
        if not np.isclose(val, 0, atol = 1e-5):
            return i
    return -1

Let's practice with the same matrix as before:

In [28]:
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [30]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


In [32]:
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')

Output for row 3: -1


<a name="3.4"></a>
### 3.4 - Constructing the Augmented Matrix

This function constructs the augmented matrix by combining a square matrix of size $n \times n$, representing $n$ equations with $n$ variables each, with an $n \times 1$ matrix that denotes its constant values. The function concatenates both matrices to form the augmented matrix and returns the result.

In [35]:
def augmented_matrix(A, B):
    augmented_matrix = np.hstack((A, B))
    return augmented_matrix

In [37]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


<a name="4"></a>
## 4 - Row echelon form

<a name="4.1"></a>

<a name="4.1"></a>
### 4.1 - Row Echelon Form

Example of matrix **in row echelon form**

$$M =
\begin{bmatrix}
7 & 2 & 3 \\
0 & 9 & 4 \\
0 & 0 & 3 \\
\end{bmatrix}
$$

Examples of matrices that **are not in row echelon form**

$$
A = \begin{bmatrix}
1 & 2 & 2 \\
0 & 5 & 3 \\
1 & 0 & 8 \\
\end{bmatrix}
$$

$$B = 
\begin{bmatrix}
1 & 2 & 3 \\
0 & 0 & 4 \\
0 & 0 & 7 \\
\end{bmatrix}
$$


Matrix $M$ given by:

$$
M = 
\begin{bmatrix} 
* & * & * & \\
0 & \text{pivot} & * \\
0 & \text{value} & * 
\end{bmatrix}
$$


- Scale $R_1$ by the inverse of the pivot:

$$
\text{Row 1} \rightarrow \frac{1}{\text{pivot}} \cdot \text{Row } 
$$

Resulting in the updated matrix with the pivot for row $1$ set to $1$:

$$
M = 
\begin{bmatrix} 
* & * & * & \\
0 & 1 & * \\
0 & \text{value} & * 
\end{bmatrix}
$$

Next, to eliminate the value below the pivot in row $1$, I am going to apply the following formula:

$$
\text{Row 2} \rightarrow \text{Row 2} - \text{value}\cdot \text{Row 1}
$$

This transformation yields the modified matrix:

$$
M = 
\begin{bmatrix} 
* & * & * & \\
0 & 1 & * \\
0 & 0 & * 
\end{bmatrix}
$$

**Note that the square matrix $A$ needs to be in row-echelon form. However, every row operation conducted must also affect the augmented (constant) part.** 

Consider the following system of equations:


$$
\begin{align*}
2x_2 + x_3 &= 3 \\
x_1 + x_2 +x_3 &= 6 \\
x_1 + 2x_2 + 1x_3 &= 12
\end{align*}
$$

Consequently, the square matrix $A$ is formulated as:

$$
A = 
\begin{bmatrix} 
0 & 2 & 1 & \\
1 & 1 & 1 & \\
1 & 2 & 1 & 
\end{bmatrix}
$$

The column vector (a matrix of size $n \times 1$) is represented by:

$$
B = 
\begin{bmatrix} 
3\\
6\\
12
\end{bmatrix}
$$

Combining matrices $A$ and $B$ yields the augmented matrix $M$:

$$
M = 
\begin{bmatrix} 
0 & 2 & 1 & | & 3 \\
1 & 1 & 1 & | & 6 \\
1 & 2 & 1 & | & 12 
\end{bmatrix}
$$

**Step 1:**

Commencing with row $0$: The initial candidate for the pivot is always the value in the main diagonal of the matrix. Denoting row $0$ as $R_0$:

$$R_0= \begin{bmatrix} 0 & 2 & 1 & | & 3 \end{bmatrix}$$

The value in the main diagonal is the element $M[0,0]$ (the first element of the first column). The first row can be accessed by performing $M[0]$, i.e., $M[0] = R_0$.

The first row operation involves **scaling by the pivot's inverse**. Since the value in the main diagonal is $0$, necessitating a non-zero value for scaling by its inverse, we must switch rows in this case. Note that $R_1$ has a value different from $0$ in the required index. Consequently, switching rows $0$ and $1$:

$$R_0 \rightarrow R_1$$
$$R_1 \rightarrow R_0$$

Resulting in the updated augmented matrix:

$$
M = 
\begin{bmatrix} 
1 & 1 & 1 & | & 6 \\
0 & 2 & 1 & | & 3 \\
1 & 2 & 1 & | & 12 
\end{bmatrix}
$$

Now, the pivot is already $1$, eliminating the need for row scaling. Following the formula:

$$ R_1 \rightarrow  R_1 - 0 \cdot R_0 = R_1$$

Therefore, the second row remains unchanged. Moving to the third row ($R_2$), the value in the augmented matrix below the pivot from $R_0$ is $M[2,0]$, which is $1$.

$$R_2 = R_2 - 1 \cdot R_0 = \begin{bmatrix} 0 & 1 & 0 & | & 6  \end{bmatrix}$$

Resulting in the modified augmented matrix:

$$
M = 
\begin{bmatrix} 
1 & 1 & 1 & | & 6 \\
0 & 2 & 1 & | & 3 \\
0 & 1 & 0 & | & 6
\end{bmatrix}
$$

Progressing to the second row ($R_1$), the value in the main diagonal is $2$, different from zero. Scaling it by $\frac{1}{2}$:

$$R_1 = \frac{1}{2}R_1$$

Resulting in the augmented matrix:

$$
M = 
\begin{bmatrix} 
1 & 1 & 1 & | & 6 \\
0 & 1 & \frac{1}{2} & | & \frac{3}{2} \\
0 & 1 & 0 & | & 6
\end{bmatrix}
$$

Now, there's only one row below it for row replacement. The value just below the pivot is located at $M[2,1]$, which is $1$. Thus:

$$R_2 = R_2 - 1 \cdot R_1 = \begin{bmatrix} \phantom{-}0 & \phantom{-}0 & -\frac{1}{2} & | & \phantom{-}\frac{9}{2} \end{bmatrix} $$

Resulting in the augmented matrix:


$$
M = 
\begin{bmatrix} 
\phantom{-}1 & \phantom{-}1 & \phantom{-}1 & | & \phantom{-}6 \\
\phantom{-}0 & \phantom{-}1 & \phantom{-}\frac{1}{2} & | & \phantom{-}\frac{3}{2} \\
\phantom{-}0 & \phantom{-}0 & -\frac{1}{2} & | & \phantom{-}\frac{9}{2} 
\end{bmatrix}
$$

Finally, normalizing the last row as

$$R_2 = -2 \cdot R_2$$

The resulting matrix is

$$
M = 
\begin{bmatrix} 
\phantom{-}1 & \phantom{-}1 & \phantom{-}1 & | & \phantom{-}6 \\
\phantom{-}0 & \phantom{-}1 & \phantom{-}\frac{1}{2} & | & \phantom{-}\frac{3}{2} \\
\phantom{-}0 & \phantom{-}0 & \phantom{-}1 & | & -9 
\end{bmatrix}
$$

Thus, the matrix is now in row echelon form with unitary pivots.

<a name="4.2"></a>
### 4.2 - Row Echelon Form function

In [46]:
def row_echelon_form(A, B):
    det_A = np.linalg.det(A)

    if np.isclose(det_A, 0) == True:
        return "Singular System"
    A = A.copy()
    B = B.copy()

    num_rows = len(A)
    M = augmented_matrix(A, B)
    for row in range(num_rows):
        pivot_candidat = M[row, row]

        if np.isclose(pivot_candidat, 0) == True:
            first_non_zero_value_under_pivot_candidat = get_index_first_non_zero_value_from_column(M, row, row)
            M = swap_rows(M, row, first_non_zero_value_under_pivot_candidat)
            pivot = M[row, row]
        else:
            pivot = pivot_candidat
        M[row] = 1/pivot * M[row]
        for j in range(row + 1, num_rows):
            value_below_pivot = M[j, row]
            M[j] = M[j] - value_below_pivot*M[row]
    return M
            

In [48]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

array([[1, 2, 3, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0]])

<a name="5"></a>
## 5 - Back substitution

The final step of the algorithm involves back substitution, a crucial process in obtaining solutions for the linear system. The formula employed is:


$$\text{Row above} \rightarrow \text{Row above} - \text{value} \cdot \text{Row pivot}$$

In this equation, $\text{value}$ denotes the value above the pivot, which initially equals 1.

$$
M = 
\begin{bmatrix} 
\phantom{-}1 & -1 & \phantom{-}\frac{1}{2} & | & \phantom{-}\frac{1}{2} \\
\phantom{-}0 & \phantom{-}1 & \phantom{-}1 & | & -1 \\
\phantom{-}0 & \phantom{-}0 & \phantom{-}1 & | & -1 
\end{bmatrix}
$$

Starting from bottom to top:

- $R_2$:

- -  $R_1 = R_1 - 1 \cdot R_2 = \begin{bmatrix} 0 & 1 & 0 & | & 0 \end{bmatrix}$
- - $R_0 = R_0 - \frac{1}{2} \cdot R_2 = \begin{bmatrix} 1 & -1& 0 & | & 1 \end{bmatrix}$

The resulting matrix is then

$$
M = 
\begin{bmatrix} 
\phantom{-}1 & -1 & \phantom{-}0 & | & \phantom{-}1  \\
\phantom{-}0 & \phantom{-}1 & \phantom{-}0 & | & \phantom{-}0 \\
\phantom{-}0 & \phantom{-}0 & \phantom{-}1 & | & -1 
\end{bmatrix}
$$

Moving to $R_1$:

- $R_1$:

- - $R_0 = R_0 - \left(-1 \cdot R_1 \right) = \begin{bmatrix} 1 & 0 & 0 & | & 1 \end{bmatrix}$

And the final matrix is

$$
M = 
\begin{bmatrix} 
\phantom{-}1 & \phantom{-}0 & \phantom{-}0 & | & \phantom{-}1  \\
\phantom{-}0 & \phantom{-}1 & \phantom{-}0 & | & \phantom{-}0 \\
\phantom{-}0 & \phantom{-}0 & \phantom{-}1 & | & -1
\end{bmatrix}
$$

The solution is just the values in the augmented column! In this case,
$$
x_0 = 1 \ \ x_1 =0\ \ x_2 = -1
$$

<a name="5.1"></a>
### 5.1 - Back substitution function

In [54]:
def back_substitution(M):
    M = M.copy()
    num_rows = M.shape[0]

    for row in reversed(range(num_rows)):
        substitution_row = row
        index = get_index_first_non_zero_value_from_row(M, substitution_row, augmented = True)
        for j in range(row - 1, -1, -1):
            row_to_reduce = M[j, :]
            value = M[j, index]
            row_to_reduce = row_to_reduce - value*M[substitution_row]
            M[j, :] = row_to_reduce
    solution = M[:, -1]
    return solution

<a name="6"></a>
## 6 - The Gaussian Elimination

<a name="6.1"></a>
### 6.1 - Bringing it all together

In [57]:
def gaussian_elimination(A, B):
    row_echelon_M = row_echelon_form(A, B)

    if not isinstance(row_echelon_M, str): 
        solution = back_substitution(row_echelon_M)
    return solution

<a name="7"></a>
## 7 - Test with any system of equations!

In [60]:
equations = """
3*x + 6*y + 6*w + 8*z = 1
5*x + 3*y + 6*w = -10
4*y - 5*w + 8*z = 8
4*w + 8*z = 9
"""

variables = 'x y w z'
A = np.array([[3, 6, 6, 8],
       [5, 3, 6, 0],
       [0, 4, -5, 8],
       [0, 0, 4, 8]])

B = np.array([[1.],
       [-10],
       [8],
       [9]])


sols = gaussian_elimination(A, B)

if not isinstance(sols, str):
    for variable, solution in zip(variables.split(' '),sols):
        print(f"{variable} = {solution:.4f}")
else:
    print(sols)

x = -1.5414
y = -0.5223
w = -0.1210
z = 1.1855
